# Generated by Django 4.1 on 2022-11-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='stream_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist_app.streamplatform'),
        ),
    ]
